### ISSUE TITLE
Canonical repository

### ISSUE THREAD

**Issue by xla** [zefchain/bcs#4]
Hej, I'm trying to understand what the relationship is between this repository located under [zefchain/bcs](https://github.com/zefchain/bcs/) and [diem/bcs](https://github.com/diem/bcs/). While this one seems to be the source for the crate published to crates.io the diem one doesn't mention this fork and has a divergent history from what I can tell. Would you mind clarifying?

**Comment by ma2bd** [comment]
We're a few ex-Facebookers and original authors of BCS maintaining this crate because we need it for our projects. I didn't know about the other repository until recently.

**Comment by xla** [comment]
Thanks for the clarification.
